version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/London"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    groups:
      packages:
        patterns:
          - "*"
    ignore:
      - dependency-name: "FsUnit.Xunit"
        update-types: ["version-update:semver-major"]
      - dependency-name: "FluentAssertions"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/London"
    groups:
      packages:
        patterns:
          - "*"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"